import sqlite3
conexion = sqlite3.connect("db/inventario.db")
cursor = conexion.cursor()
cursor.execute("DELETE FROM incidencias")
cursor.execute("DELETE FROM activos")
cursor.execute("DELETE FROM sqlite_sequence WHERE name='activos'")
cursor.execute("DELETE FROM sqlite_sequence WHERE name='incidencias'")
conexion.commit()
conexion.close()
print("Hecho")